-- Remove permissões de setor / overrides que não pertencem ao catálogo de template de setor
-- (alinhado a `SECTOR_ASSIGNABLE_*` em permission-catalog.ts).

DELETE FROM sector_permissions
WHERE action NOT IN (
  'view:dashboard',
  'view:metrics',
  'view:unified_dashboard',
  'view:condominiums',
  'switch:condominium',
  'view:structure',
  'view:residents',
  'view:all_residents',
  'view:complaints',
  'view:all_complaints',
  'view:own_complaints',
  'create:complaint',
  'edit:complaint',
  'update:complaint_status',
  'update:complaint_priority',
  'delete:complaint',
  'view:anonymous_complaints',
  'comment:complaint',
  'resolve:complaint',
  'return:complaint',
  'reassign:complaint',
  'view:messages',
  'view:message_history',
  'send:message',
  'send:bulk_message',
  'send:to_all',
  'send:to_tower',
  'send:to_floor',
  'send:to_unit',
  'view:whatsapp_status',
  'view:history',
  'view:all_history',
  'view:announcements',
  'create:announcement',
  'view_sector_dashboard',
  'view_sector_complaints',
  'submit:csat'
);

DELETE FROM sector_member_permission_overrides
WHERE action NOT IN (
  'view:dashboard',
  'view:metrics',
  'view:unified_dashboard',
  'view:condominiums',
  'switch:condominium',
  'view:structure',
  'view:residents',
  'view:all_residents',
  'view:complaints',
  'view:all_complaints',
  'view:own_complaints',
  'create:complaint',
  'edit:complaint',
  'update:complaint_status',
  'update:complaint_priority',
  'delete:complaint',
  'view:anonymous_complaints',
  'comment:complaint',
  'resolve:complaint',
  'return:complaint',
  'reassign:complaint',
  'view:messages',
  'view:message_history',
  'send:message',
  'send:bulk_message',
  'send:to_all',
  'send:to_tower',
  'send:to_floor',
  'send:to_unit',
  'view:whatsapp_status',
  'view:history',
  'view:all_history',
  'view:announcements',
  'create:announcement',
  'view_sector_dashboard',
  'view_sector_complaints',
  'submit:csat'
);
