-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('PENDING', 'VALIDATING', 'APPROVED', 'REJECTED');

-- AlterEnum: add new values outside of transaction
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'TRIAGE';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'WAITING_USER';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'WAITING_THIRD_PARTY';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

-- AlterEnum: add new values outside of transaction
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TRIAGE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SETOR_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SETOR_MEMBER';
